### ISSUE TITLE
Depends on obsolete pcre

### ISSUE THREAD

**Issue by glondu** [camlp5/camlp5#101]
While updating the camlp5 package in Debian, I realized that the last version (8.02.00) uses pcre, which is obsolete and will soon be removed from Debian. I see you also use re; could you use only re and not pcre, please?

**Comment by chetmurthy** [comment]
Why is pcre obsolete?  B/c right now, re is .... not a complete replacement: there are missing features.

**Comment by glondu** [comment]
> Why is pcre obsolete? 

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1000004

> re is .... not a complete replacement: there are missing features

Sure... But does camlp5 actually need those missing features?

**Comment by chetmurthy** [comment]
Oh, I see, instead of pcre, it should be pcre2.  I guess I'll need to ask the maintainer of pcre if they plan to switch to pcre2.

**Comment by chetmurthy** [comment]
There were two problems:

1. re does not implement full regex syntax: I forget which particular feature was missing, but I can look in the unit-tests of `pa_ppx_regexp` -- I remember writing tests that demonstrated this.

2. pcre allows to extract the number of capture groups, where re did not.  I sent in a patch for this, but it hasn't made it out to release.  This is necessary in order to make capture-group extract type-safe.

**Comment by glondu** [comment]
> Oh, I see, instead of pcre, it should be pcre2. I guess I'll need to ask the maintainer of pcre if they plan to switch to pcre2.

See https://github.com/mmottl/pcre-ocaml/issues/25

> There were two problems: [...]

These features do not seem used in camlp5 itself, are they?

**Comment by chetmurthy** [comment]
I think I remember the syntax that was unsupported.  Look at https://github.com/camlp5/camlp5/blob/39c8bf5829ff7bec55a6f830d4e25b5fec6dc77b/scripts/mkcamlp5.ml#L41

My memory could be faulty, but I think the syntax here was not supported by `re`.  If you search for "[%" in the file, you'll find that other uses of regular expressions in the file are all `re`, not `pcre`.  This was the one regexp that needed to use `pcre`, b/c of unsupported syntax.

It's possible that `re` has improved; I should check if they support this syntax now, and if so, then I can switch this line to use `re`.

I should note that the code in `etc/mkcamlp5.ml` is *generated* from this file in `scripts` by running a PPX rewriter to preprocess the code.

**Comment by glondu** [comment]
> My memory could be faulty, but I think the syntax here was not supported by re.

I assume you are refering to `{|\n+$|}`...? If so, I confirm and it doesn't seem difficult to fix in re... But doesn't `"\n+$"` work?

> I should note that the code in etc/mkcamlp5.ml is generated from this file in scripts by running a PPX rewriter to preprocess the code.

I can't install (with opam) pa_ppx_regexp (0.01) with the latest version of camlp5 (8.02.00): there seems to be some conflict.

**Comment by chetmurthy** [comment]
1. the  syntax `{|....|}` is a raw-string literal.  It  is otherwise just like a string.  The problem was in the regex compiler of `re` (if I remember correctly -- I might be mistaken).  I have a vague memory that "\n" didn't work -- that various "special character escapes" were not implemented.

2. Ah yes.  First, you do not need `pa_ppx_regexp` installed to build/install camlp5.  Indeed, it is the other way around: you need to install `camlp5` (and `pa_ppx`) first, in order to then install `pa_ppx_regexp`.  There is a "bootstrap" procedure in the `camlp5/scripts` directory that is *not* invoked during the build/install, that runs the PPX rewriter on `scripts/mkcamlp5.ml` and dumps its output into `etc/mkcamlp5.ml`.  That latter file is then compiled during the build/install process.

But 3. also, I need to release a new version of the various `pa_ppx_*` packages, based on the new `camlp5`.  I plan to get those pushed into the opam PR queue this week.

**Comment by glondu** [comment]
1. I know about the raw-string literal syntax, and you are right concerning `re`'s parser limitations. What I am asking is whether you really need it **in this specific case**. I will fix the "special character escapes" in `re` nonetheless, but what I am saying is that you might not need to wait for it.
2. Yes, I eventually figured out all this by myself... I just wanted to try the bootstrap procedure, since my [pull request](https://github.com/camlp5/camlp5/pull/102) touches `etc/mkcamlp5.ml`.

**Comment by chetmurthy** [comment]
Oh now I see what you're asking.  I'm loath to depend on `re` until I have strong belief in its reliability -- the same sort of belief I have in the reliability of `pcre`.  I've already rewritten a number of scripts in `camlp5` and `camlp5-buildscripts` in ocaml, where I had originally written them in `perl`, only to find that Perl's handling of various UNIX errors was different from that of OCaml, and that was problematic: the current set of releases I need to push out, are partially due to that.

So I'd very much prefer to wait until `re` supports at least the core of regular expressions that `pcre` does, before switching.

Second, I pushed out a new release of `camlp5` only a couple of weeks ago, so in any case, it would be a while before I push a new camlp5 release.  Hopefully by that time, there will be either a new `re` (with greater support for full regex syntax) or `pcre2` will be available in OCaml.

I will recheck what the gap is between `pcre` and `re` in my unit-tests, as I prepare a new release of `pa_ppx_regexp`.

**Comment by glondu** [comment]
> I should be able to switch camlp5 to use `pcre2` instead of `pcre`, as soon as `pcre2-ocaml` is released.

I am a bit disappointed, since I liked the move from C bindings to a pure OCaml library :-) Especially since the use of `pcre` in camlp5 seems anecdotal...  But I understand your point of view. Which version of `pcre2` did you use? [This one](https://github.com/tobil4sk/pcre2-ocaml)?

> I've offered to help with that process, over at their github repo.

I've seen your offer [here](https://github.com/mmottl/pcre-ocaml/issues/25#issuecomment-1676463732). @tobil4sk has clearly [expressed](https://github.com/mmottl/pcre-ocaml/issues/25#issuecomment-1483806201) that he doesn't want to be responsible for `pcre2` (nor do I), so I think you should just take the lead: make a fork, and release `pcre2-ocaml` properly yourself.

As far as Debian is concerned, the current version of camlp5 there is 8.00.04, and I started upgrading to a more recent version to prepare the transition to OCaml 5.1.0, only to realize the new dependency on `pcre` which is about to be removed from Debian :-( I would like a version without this dependency, hence my [pull request](https://github.com/camlp5/camlp5/pull/102), which I [applied](https://salsa.debian.org/ocaml-team/camlp5/-/commit/118251f904937a2c9d17388cef582483289cd9a8) to the Debian package (but have not uploaded yet). Of course, I would like to avoid maintaining such a divergence.

So, when I will/can upload a new camlp5 in Debian, I will used my patched version (using just `re`). And when you take upstream leadership on `pcre2` and make a release, I will also upload it to Debian. Only then, I will be able to update to an unpatched camlp5 using `pcre2`.

**Comment by glondu** [comment]
I've submitted an ITP (Intent To Package) bug for pcre2-ocaml, with a detailed explanation of the situation: https://bugs.debian.org/1049405

**Comment by glondu** [comment]
I've submitted a pull request to add support for `\n` in `Re.Perl` (and `Re.Pcre`): https://github.com/ocaml/ocaml-re/pull/227

**Comment by chetmurthy** [comment]
Excellent!  Thank you!

**Comment by chetmurthy** [comment]
Oh great, now that `re` supports "\n" properly, I'm happy to switch to using that.  I'll also be supporting `pcre2` (and releasing it soon) b/c .... well, there's no point in ditchng pcre when `re` is so new.  But `pa_ppx_regexp` already supported both `re` and `pcre`: adding `pcre2` wasn't hard (I already did it -- just need to wait for pcre2 to be released, to release this support).

Thank you for updating `re`!

**Comment by glondu** [comment]
Note that `pa_ppx_regexp` is not in Debian at the moment, so I'm less pressed to remove `pcre` support from it (but will need to if it ever makes its way to Debian). I am more concerned about `camlp5` itself, hence my [pull request](https://github.com/camlp5/camlp5/pull/102). Could you have a look at it, please? Can you estimate the time you need to release a version of `camlp5` that does not depend on `pcre`? FYI, `pcre` is scheduled to be removed from testing on [21 September](https://tracker.debian.org/pkg/pcre-ocaml).

**Comment by chetmurthy** [comment]
I've looked at it, but since you've upgraded `re`, there's no need for it -- I can just switch to `re`.  I'll be doing that.  Since you don't need opam release -- just a "release" in github, I think it will be easy to get that done by 21 Sept.

**Comment by chetmurthy** [comment]
Hi, I just released camlp5 8.02.01; it should go out via opam at some point (there's a backlog there, so I don't know how long it'll take -- might be a couple of weeks) but since you're packaging for Debian, I assume you aren't affected by this.  In any case, it builds without pcre, and only uses pcre2 for tests.

**Comment by glondu** [comment]
> I just released camlp5 8.02.01 [...] it builds without pcre, and only uses pcre2 for tests

Thank you. I've updated it in Debian.
