### ISSUE TITLE
Comment is deleted

### ISSUE THREAD

**Issue by sagotch** [camlp5/camlp5#41]
```ocaml
let print_err_unknown conf _base (f, s, o) =
(* #ifdef API *)
  if not !Api_conf.mode_api then begin
(* #endif *)
  let title _ = Wserver.printf "%s" (capitale (transl conf "error")) in
  Hutil.rheader conf title;
  Wserver.printf "%s%s <strong>%s.%d %s</strong>\n"
    (capitale (transl conf "unknown person")) (transl conf ":") f o s;
  print_return conf;
  Hutil.trailer conf;
(* #ifdef API *)
    end;
(* #endif *)
  let err =
    Printf.sprintf "%s%s <strong>%s.%d %s</strong>\n"
      (capitale (transl conf "unknown person")) (transl conf ":") f o s
  in
  raise @@ ModErr err
```
with `camlp5o pr_o.cmo`, it gives:
```ocaml
let print_err_unknown conf _base (f, s, o) =
(* #ifdef API *)
  if not !(Api_conf.mode_api) then
    begin let title _ =
      Wserver.printf "%s" (capitale (transl conf "error"))
    in
      Hutil.rheader conf title;
      Wserver.printf "%s%s <strong>%s.%d %s</strong>\n"
        (capitale (transl conf "unknown person")) (transl conf ":") f o s;
      print_return conf;
      Hutil.trailer conf
    end;
(* #endif *)
  let err =
    Printf.sprintf "%s%s <strong>%s.%d %s</strong>\n"
      (capitale (transl conf "unknown person")) (transl conf ":") f o s
  in
  (@@) raise (ModErr err)
```

**Comment by chetmurthy** [comment]
[I'm a camlp5 user, but decided I should try to figure out what's going on here.  So .... what I write could be very wrong, and Daniel is obviously the authority on camlp5.  I'm just trying to help out.]

Hi, I did some digging on this, and have some answers and a question.  First, here's a simplified version of your code [with more comments in order to elicit other behaviours].  Can you confirm that this doesn't remove any critical attributes of your code?  (I don't think it does, but always good to check):
```
let foo x =
(* com1 *)
  if false then
    (* com2 *)
 begin
(* com3 *)
  A ;
(* com4 *)
end
(* com5 *)
  else
(* com6 *)
 B;
(* com7 *)
  C
```
With some patches to camlp5, processing this as you indicate yields
```
let foo x =
  (* com1 *)
  if false then
    (* com2 *)
 
(* com3 *)
    A
  else
    (* com6 *)
    B;
  (* com7 *)
  C
```
The "deleted comments" in your example correspond to comments "com3" and "com4" above.  As you can see, comments "com4" and "com5" have been deleted.  I thought I'd explain why, and then maybe we could discuss how much you want these comments to be preserved.

camlp5 preserves comments that appear before certain AST nodes (expressions, patterns, struct-items, maybe others).  That's it.  So any other comments, end up getting dropped.   Heck, I haven't yet figured out why "com2" got preserved (but I'm digging on that).  So your comment "com4", (nor "com5") since it is not *before* any of the "preserve comments" AST nodes, doesn't get preserved.

The general idea, from what I can work out in camlp5, is that comments are NOT guaranteed to be preserved.  camlp5 makes a best-effort attempt to preserve them, but since it is doing rewriting (in your case, a "begin...end" with a single expression inside it is rewritten when possible to just the expression), there is no guarantee that all the comments can be preserved without some further work to "move comments around" in the face of rewriting.

I don't know if you're counting on all comments to be preserved, but if so, I suspect you'll find that that's an unrealistic expectation.

Can you comment on what you're looking for in the way of comment-preservation?

**Comment by sagotch** [comment]
I guess that I'll expect that every comments get preserved because it not the job of camp5 to say what comment is important and which one is not.

My use case concern mixing campl5 with ppx, using comments in files processed by campl5 + sed to uncomment resulting file.

I can not really control where the comment should go. I can tweak the ast so camlp5 would not drop the comment, so I can always use a workaround (I guess) but you should not have to use such hack.

**Comment by chetmurthy** [comment]
So what you really want, is support for "PPX extension pass-thru" in camlp5, right?

**Comment by chetmurthy** [comment]
Two more thoughts:

(1) I also use both camlp5 and PPX.  I just put the code that uses these two things in different files.  It's a little inconvenient, but seems to work pretty well.

(2) I think it's unrealistic to expect that comments will be preserved except on a best-effort basis.  Quite simply, comments are "not significant" ,  Sure, camlp5 tries to preserve 'em.  But really, expecting more than that is .... asking for pain.

**Comment by sagotch** [comment]
I am actually jot asking for anything, I just filled a bug report because it seems like a bug to me. If comment are that significant, why would camlp5 preserve some of them ? Just drop everything if it is considered useless.

But I agree that ppx and camlp5 incompatibility is my actual problem.

**Comment by chetmurthy** [comment]
I can't speculate on @roglo 's motives in preserving some comments in the output of camlp5, but generally, when people write preprocessors, they -do- think about the idea (and then perhaps dismiss it).  After all, comments are very useful for understanding, in the very/very/very large output from preprocessing some file, what the heck happened, right?

But critically, comments are "semantically not significant".  It is true, that some people use comments as a sort of "poor man's syntax extension" (I've done it myself in Java, sigh), but this is 100% guaranteed to be unsupported.  Especially because camlp5, like the LISP/Scheme systems from which it descends (intellectually), is committed to viewing the AST as the real subject of all investigation/computation, not the -text- of the program.  And ASTs don't contain comments, or at least, the comments they contain are semantically irrelevant.

I'll look into what's required to support "PPX extension passthru" in camlp5.

**Comment by roglo** [comment]
It is very difficult to keep all comments and/or print them at the good place, especially when it is pretty printing and not just indenting.

It is a old problem. I remember they talked about that in the 70ies about the language Pascal.

In Camlp5, each comment is supposed to be associated with a node in the syntax tree but it is not always possible to do so and/or associate the good comment to the good node. Some comments may disappear indeed. I tried to do my best and, maybe sometimes, there is missing code in the pretty printer but the general idea is that comments are just an attempt for the improvement of the pretty printing. It is not guaranteed to work in all circumstances.

**Comment by chetmurthy** [comment]
Hi, could you close this issue, since it's no longer a bug?
