### ISSUE TITLE
4.11.1 support

### ISSUE THREAD

**Issue by rwmjones** [camlp5/camlp5#61]
4.11.1 support is missing.  However it seems identical in respect of parsing to 4.11.0 and I was able to make camlp5 work simply by doing:
```
pushd ocaml_stuff
ln -s 4.11.0 4.11.1
popd
pushd ocaml_src/lib/versdep
ln -s 4.11.0.ml 4.11.1.ml
popd
```

**Comment by chetmurthy** [comment]
Yes.  This is a long-standing problem with camlp5's configuration system: even though Ocaml bugfix releases are guaranteed to not change the AST types, camlp5's source must be explicitly updated each time a bugfix happens.  I think this is because there might be fixes in -code- associated with the AST.

But this is really low-likelihood, and so I wonder if maybe the rule ought to be that instead of failing when (e.g.) 4.11.1 has no configuration information available in the camlp5 source, it could just revert to the most-recent bugfix for the same release (E.g. 4.11.0 in this case).  This might result in failures and bugs, but not likely, and it still seems better than simply -failing- outright.

What do you think?

**Comment by rwmjones** [comment]
I guess maybe some kind of "longest match", so if there's a `4.11.1` directory, it uses that, otherwise it falls back to `4.11` ...

**Comment by chetmurthy** [comment]
Heh, I was in the process of writing a long reply about how if there existed a 4.11.5 directory, and we were looking for 4.11.6, then 4.11.5 should be the one chosen.  But that would require much more BASH code than just ripping off that ".6" at the end and checking if that directory exists.

I'm not a big fan of bash for complex scripts, much preferring Perl every time I can.  So your suggestion will make it possible for me to preserve the config file in bash, rather than converting it to mostly-perl.

Thanks!

**Comment by chetmurthy** [comment]
I'm almost done with the fix.  I've updated the source-tree to contain support for 4.11.1, but  before doing so, fixed the configuration process in the manner described in my previous comment.  But since there -is- support for 4.11.1 in the version-to-be-released, you won't see that new configuration process, unless you explicitly delete the 4.11.1 support files, and then configure.

**Comment by chetmurthy** [comment]
OK, you can checkout from camlp5/camlp5, and get a version that should work.  Also, I published a new release, so eventually that'll make its way to opam.

Thank you for catching this.
