### ISSUE TITLE
Installation failure with ocaml 4.11.1

### ISSUE THREAD

**Issue by glondu** [camlp5/camlp5#63]
camlp5 7.12 fails to install with ocaml 4.11.1. Maybe it's time to make a new release?

**Comment by chetmurthy** [comment]
I'll prepare a bugfix release today and reply to this issue when it's been committed.  I'll release it via opam, but that will take a few days to make it thru approvals.  There is a fixed version 8.00~alpha04 that is available via opam.  Have you tried that?  If you had problems with that, I I would of course be most eager to do whatever is required to resolve them.  If you have software that uses camlp5, that I can update for you to 8.00, I would be happy to do that, also.

**Comment by chetmurthy** [comment]
Hello, two things:

(1) https://github.com/camlp5/camlp5/tree/rel713-fixes

this should work for ocaml 4.11.1 and all prior releases.

(2) I've pushed a new release into opam, and after it traverses the approval machinery, it should be available.

**Comment by glondu** [comment]
Note that I am the Debian packager for ocaml, preparing the transition from 4.08.1 to 4.11.1.

> There is a fixed version 8.00~alpha04 that is available via opam. Have you tried that?

No. It doesn't get installed when I `opam install` the packages I am insterested in.

> If you have software that uses camlp5, that I can update for you to 8.00, I would be happy to do that, also.

Why, is there a major incompatibility? What's the status of 8.00 w.r.t. release management?

The Debian packages using camlp5 are geneweb, haxe, hol-light, lablgtk3, ledit, matita, orpie and ulex0.8 (which is ulex-camlp5 in opam).

**Comment by chetmurthy** [comment]
The problem is, that camlp5 was basically not updated for a good number of ocaml releases, to support new ocaml syntax.  So when I finally took over maintenance, I had to add a -ton- of new AST support, and it was difficult for me to avoid breaking at least -some- of the APIs.  The largest part of this was related to PPX attributes/extensions, for which there was no support prior to camlp5 8.00.  None at all.

Typically, code that uses only camlp5 quotations and some grammars, doesn't need to change.  But sometimes there are minor bugs -- places where a pair needs to become a triple, with the third part either ignored, or an empty-list ( == "no attributes").

In any case, I will proceed to check these packages and see if any of them need to be updated to support camlp5 8.00.  I already just did with geneweb, and it built without any problems.  I have also already updated ledit, but have not yet released it (though Daniel has given permission for me to do).

Once I've verified that all the packages in your list work fine with camlp5 8.00, I'll let you know.  Would that be OK?

**Comment by glondu** [comment]
> Once I've verified that all the packages in your list work fine with camlp5 8.00, I'll let you know. Would that be OK?

That would be fantastic.

**Comment by chetmurthy** [comment]
Stephane, I've some some verification, and thought I should report to you the results.

(1) btw, ocaml 4.11.1 support is in camlp5 7.13 and 8.00~alpha04, both of which have been released.

(2) I verified that:

  - haxe
  - geneweb
  - ulex-camlp5 (sent them a patch a while ago, and it's been merged, but I don't know when it'll appear in a release)
  - lablgtk3
  - ledit (I released a new version today)
  - orpie

all build with the latest camlp5 8.00~alpha04.

I don't quite understand how to build the matita package -- it seems to depend on packages that are no longer available, and I could not find it using debian package search.  Could you please advise?

I have contacted the author of hol-light, and hope he'll respond and I can figure out the best way to upgrade the package:   They have copied a number of camlp5 files, and I don't quite understand why, so it's not so clear how to proceed.

**Comment by glondu** [comment]
> Stephane, I've some some verification, and thought I should report to you the results. [...]

Wonderful.

> I don't quite understand how to build the matita package -- it seems to depend on packages that are no longer available, and I could not find it using debian package search. Could you please advise?

In Debian, the matita package is broken at the moment, hence not in testing (nor stable). But it seems alive upstream. I intend to contact them when the transition to OCaml 4.11.1 (or newer) is done. Maybe @sacerdot or @gares can comment?

> I have contacted the author of hol-light, and hope he'll respond and I can figure out the best way to upgrade the package: They have copied a number of camlp5 files, and I don't quite understand why, so it's not so clear how to proceed.

OK. Note that [patches are applied](https://salsa.debian.org/ocaml-team/hol-light/-/tree/master/debian/patches) in the Debian package, in particular [this one](https://salsa.debian.org/ocaml-team/hol-light/-/blob/master/debian/patches/0004-Fix-compilation-with-camlp5-7.11.patch). I seem to have forgotten to forward it upstream, but it might help you.

**Comment by glondu** [comment]
The version of camlp5 currently in Debian testing (and stable) is 8.00.04. I guess this issue is no longer relevant.
