### ISSUE TITLE
Extending pa_macro

### ISSUE THREAD

**Issue by LdBeth** [camlp5/camlp5#69]
Metaprl extends the preprocessor with a new command `INCLUDE`, that can load a macro definition file. So I'm trying to extend `pa_macro` instead of rewriting the entire file.

However writing something like this raise the error:
```
73 | value foo = Pa_macro.defined_version ;
                 ^^^^^^^^^^^^^^^^^^^^^^^^
Error: Unbound value Pa_macro.defined_version

```
while write `value foo = Pa_macro.defined` works. Is there anything special with `defined_version` in revised syntax?

The building argument I use: `ocamlc.opt -warn-error Aez-3-7-29-34-37-44-45-50-60-67 -w Aez-3-7-29-34-37-44-45-50-60-67 -thread -pp 'camlp5r -I /usr/local/lib/ocaml/camlp5 -nolib -loc _loc' -g -I . -I /usr/local/lib/ocaml/compiler-libs -I /usr/local/lib/ocaml/camlp5 -c pa_include.ml`

and I have 
```
#load "pa_macro.cmo";
#load "pa_extend.cmo";
#load "q_MLast.cmo";

open Pcaml;
open Pa_macro;
```

at the beginning of my file.

_Originally posted by @LdBeth in https://github.com/camlp5/camlp5/issue_comments/711149362_

Also, I want to remove the following rule added to str_item defined in pa_macro, because I need to write something like
```
IFDEF VERBOSE_EXN THEN
       DEFINE FAIL = fail
       DEFINE DO_FAIL = fail_addr fail
    ELSE
       DEFINE FAIL = NOTHING
       DEFINE DO_FAIL = RAISE_GENERIC_EXN
    END
```
but the original pa_macro definition doesn't allow multiple macro definitions in if then else clause. How can I use DELETE_RULE to do that? Seems it is impossible to match this rule.

```
EXTEND
  GLOBAL: dexpr expr patt str_item sig_item constructor_declaration match_case
    label_declaration;
  str_item: FIRST
    [ [ x = str_macro_def ->
          match x with
          [ SdStr sil -> do {
              let sil = Pcaml.unvala sil in
              List.iter
                (fun
                 [ MLast.StDir loc n dp -> apply_directive loc n dp
                 | _ -> () ])
                sil;
              match sil with
              [ [si] -> si
              | sil -> <:str_item< declare $list:sil$ end >> ]
            }
          | SdDef x eo -> do { define eo x; <:str_item< declare end >> }
          | SdUnd x -> do { undef x; <:str_item< declare end >> }
          | SdNop -> <:str_item< declare end >> ] ] ]
  ;
...

**Comment by chetmurthy** [comment]
I'll take a look at this soon, but two thoughts:
(1) Don't expect "DELETE RULE" to work.  It's nice that somehow it works sometimes.  But really, it's a hack, and has all sorts of limitations.
(2) Why don't you just `cppo` ?  I mean, the problem with `pa_macro` is that it works within the limitations of the AST, and that is -very- problematic.  It's never going to be able to do all the things one would want from a macro-preprocessor, because almost by definition, a macro preprocessor is going to want to cross syntactic categories.

I don't see any reason to stop support `pa_macro`.  But I've found it very limiting, and typically I end up reaching for either `cppo` or (heck) `cpp -E` for my macro-preprocessing needs (e.g. in `camlp5/test` and `pa_ppx`/tests-ounit`.

**Comment by chetmurthy** [comment]
Also, why is
```
IFDEF VERBOSE_EXN THEN
       DEFINE FAIL = fail
    ELSE
       DEFINE FAIL = NOTHING
    END
IFDEF VERBOSE_EXN THEN
       DEFINE DO_FAIL = fail_addr fail
    ELSE
       DEFINE DO_FAIL = RAISE_GENERIC_EXN
    END
```
insufficient?

**Comment by LdBeth** [comment]
One reason not to use `cppo` is, there're some interesting constructs been defined here: 

the scope of `body` is only inside the define block.

```
    DEFINE body = try equal_term [] t1 t2 with Failure _ -> false
      IN
      IFDEF VERBOSE_EXN THEN
         if !debug then eprintf "debug msg"
         else body
      ELSE
         body
      END
```
> If a macro is define to = NOTHING, and then used as an argument to a function,
  this will be equivalent to function taking one less argument. Similarly,
  passing NOTHING as an argument to a macro is equivalent to "erasing" the
  corresponding parameter from the macro body.
```
   IFDEF VERBOSE_EXN THEN
      DEFINE ATERM = (a, term)
   ELSE
      DEFINE ATERM = NOTHING
   END
...
   let getnth ATERM terms i =
      if i = 0 then
         raise (Invalid_argument "Term_addr_ds.getnth: got Subterm 0")
      else
         List.nth terms (make_index ATERM i (List.length terms))
```

**Comment by chetmurthy** [comment]
(1) this DEFINE ... IN is new: you haven't mentioned it before.  And it is *definitely* not something I would want to support.  I'm pretty sure that the point of `pa_macro` when it was written, was to provide some of the capability of `cpp`.  Not to invent a new "syntactic language" on top of Camlp5, directly in the parser.
(2) I don't understand your example regarding NOTHING.  If I write
```
#define ATERM NOTHING
```
then uses of ATERM are expanded to `NOTHING`, not to an empty string.

(3) I think it might be useful to write down a full list of the extensions you want, with examples of each.  And again, I -do- think you should think about using `cppo`.  `pa_macro` will always be limited, because it does its work on ASTs, not strings of lexemes.

**Comment by LdBeth** [comment]
The `DEFINE IN` construct is an undocumented feature used in the source that just burst out when I'm trying with CamlP5's `pa_macro`.

for the `ATERM` example, when `DEFINE ATERM = (a, term)` the code is expanded to

```
let getnth (a, term) terms i =
   if i = 0 then
      raise (Invalid_argument "Term_addr_ds.getnth: got Subterm 0")
   else
      List.nth terms (make_index (a, term) i (List.length terms))
```

and when `DEFINE ATERM = NOTHING` it becomes

```
let getnth terms i =
   if i = 0 then
      raise (Invalid_argument "Term_addr_ds.getnth: got Subterm 0")
   else
      List.nth terms (make_index i (List.length terms))
```

The `INCLUDE` extension is straightforward.

Other concerns on changing to `cppo` is that I don't know how well it is with `ocamldep`, which is used as the dependency analyzer in the building system.

**Comment by chetmurthy** [comment]
What?  I searched the source of both the current release and the 7.11 release for
`"NOTHING"` and `"IN"` and found no hits.  Can you point me at the lines where this function is implemented?

**Comment by LdBeth** [comment]
Sorry, I mean it is in the fork of `pa_macro` used by MetaPRL. it has `NOTHING` and `INCLUDE` feature documented in the header comments, but didn't mentioned there's a `DEFINE IN` constructs.

https://github.com/owo-lang/metaprl/blob/master/util/pa_macro.ml

**Comment by chetmurthy** [comment]
OK, so I think you should probably keep your fork of `pa_macro`.  Here's the thing:

(1`) `pa_macro` is a macro-preprocessor for -structures- -- for ASTs.  This should mean that it respects the structure of the AST
(2) DEFINE...IN goes along in this direction, even if I find it problematic.
(3) but this `NOTHING` thing ... .reading the comments, it's clear that (a) it only works in certain places, and (b) it intrinsically involves  a restructuring of the AST.  And the thing is, the reason they have to do that is clear: the `NOTHING` construct is really an attempt to get some of the behaviour of "lexical-level macro-preprocessing", even though `pa_macro` is an AST-level macro-preprocessor.

This is a mixing of methods and goals that I think would be  bad to import into camlp5, especially since `pa_macro` is definitely not something to extend without great need.  I mean, the right way to do everything you're asking for, is to integrate  `cppo` directly into the lexer -- and this is probably pretty feasible  (when I have time).

Also, something else: I see that you use `#load` directives a lot.  One of the goals of the current release-stream, is to get to where nobody does that except in the toplevel.  Because instead of #load, there is `ocamlfind -package`.  The latter is declarative in a way  that `#load` is not.  And furthermore, `#load` is not controllable, in the sense that you can't really control from where files are loaded.  With findlib, at least you know where the files come from, and honestly, I think it is possible to do a -better- job of controlling where files come from, than they do already.

**Comment by LdBeth** [comment]
Thank you for letting me know that `cppo` is a more proper solution. For the `#load` thing, I left that as is because the file was copied directly from the release directory, but I'm happy to know that it is not necessary to get things working.

**Comment by chetmurthy** [comment]
closing.
