### ISSUE TITLE
regression in META file

### ISSUE THREAD

**Issue by olafhering** [camlp5/camlp5#75]
d23defc36bfd75fca0dd929e2649d3f53eab11b4 caused a regression. `$(DESTDIR)` must not appear in any file. It must be used just for runtime paths during `make install`.

````diff
--- a/etc/Makefile
+++ b/etc/Makefile
@@ -106,7 +106,7 @@ install:
        -$(MKDIR) "$(DESTDIR)$(LIBDIR)/$(CAMLP5N)" "$(DESTDIR)$(BINDIR)"
        $(RM) -f "$(DESTDIR)$(LIBDIR)/$(CAMLP5N)/pa_lex.cmo"
        cp $(OBJS) $(INSTALL_CMI) "$(DESTDIR)$(LIBDIR)/$(CAMLP5N)/."
-       sed -e "s|@VERSION@|$(VERSION)|" -e "s|@CAMLP5DIR@|$(DESTDIR)$(LIBDIR)/$(CAMLP5N)|" META.tpl > META
+       sed -e "s|@VERSION@|$(VERSION)|" -e "s|@CAMLP5DIR@|$(LIBDIR)/$(CAMLP5N)|" META.tpl > META
        cp META "$(DESTDIR)$(LIBDIR)/$(CAMLP5N)/."
        cp lib.sml "$(DESTDIR)$(LIBDIR)/$(CAMLP5N)/."
        cp $(CAMLP5N)o$(EXE) $(CAMLP5N)sch$(EXE) "$(DESTDIR)$(BINDIR)/."

**Comment by chetmurthy** [comment]
Hi, I only took over maintenance about a year ago, and I sure cannot claim to know all the assumptions that govern Camlp5.  Can you explain why this is?  Asking seriously.  I'd be happy to make this change, but I just want to understand what the problem is.  Currently Camlp5's build installs a "local copy" of the package in a "local-install" directory, and that works fine: the META file gets regenerated at install-time, each time, so that it has the correct directory path.

**Comment by olafhering** [comment]
`DESTDIR` is just an offset during make install, to temporary put binaries into a directory which collects binaries to create a package.

Whatever the purpose of that "local-install" directory is, if stuff is executed from there, `$(prefix)` needs adjustment to point into this "local-install" directory.

**Comment by chetmurthy** [comment]
Aha, I've understood.  If I want to install to a different location during the build-process, I need to set LIBDIR, and not DESTDIR.  Cool, I'll figure out how to do that.

**Comment by chetmurthy** [comment]
And thank you for explaining!
