### ISSUE TITLE
Compilation failure

### ISSUE THREAD

**Issue by hgouraud** [camlp5/camlp5#82]
I am maintaining a somewhat old version of GeneWeb (v6.08) which uses camlp5.
After the recent move to camlp5.8.00, GeneWeb's compilation fails with the following message: 
(environment is macOS, 10.15.7, ocaml.4.11.1, camlp5.8.00.01, opam.2.0.0)
```
Henri@iMac-H geneweb % make all
cd wserver; make opt
make[1] : on entre dans le répertoire « /Users/Henri/GitHub/hgouraud/geneweb/wserver »
camlp5r pa_extend.cmo q_MLast.cmo -o pa_macro5.ppo pa_macro5.ml
File "pa_macro5.ml", line 162, characters 51-52:
While expanding quotation "patt":
Parse error: end of input expected after [patt] (in [patt_eoi])
make[1]: *** [Makefile:11 : pa_macro5.cmo] Erreur 2
make[1] : on quitte le répertoire « /Users/Henri/GitHub/hgouraud/geneweb/wserver »
make: *** [Makefile:24 : opt] Erreur 2
```
Is there anything I should do to correct this error?
Do you need additional context?

For clarity, the new GeneWeb v7 version compiles fine in my environment!

Thanks for your help.

Henri

**Comment by chetmurthy** [comment]
Hi.  I haven't looked at the code of geneweb [or at least, if I have, it was a long time ago] but I suspect it either uses quotations or extensible grammars that are out-of-date.  As is well-known, when you add new syntax to an existing language, you can end up forcing the grammar to be changed in significant ways.  Since camlp5's extensible grammars are based on an executable grammar specification, they also are going to change, and in incompatible ways.  Then, in the passage from version 7.xx to version 8.xx, a bunch of reorganization happened, in order to support the new syntax (PPX, other things), and so quotations broke.  That's what the error-message is indicating.

I'm sorry for all these syntax-related incompatibilities.  The problem is, as I described, down to the problem of how to extend grammars when those grammars are themselves an executable framework that users can hang their own code and extensions upon.  It's a hard problem.

If you look at the newest version of geneweb in that same file (pa_macro5.ml), you can probably see where they made their fixes, and backport them.  If you have trouble, please contact me again, and I can try to help you.

Hope this helps.

**Comment by hgouraud** [comment]
Thanks for your comment.
It looks like use of camlp5 in GeneWeb v7 is reduced to a strict minimum. For my old v6.08 version, I guess I have to stay with camlp5.7.12 which worked! Migrating to 8.00, or reducing camlp5 use as in v7, would require an extensive rework of v6.08 which is beyond my ability.
I guess I can only hope that v7 will eventually support large databases with a gwc2 implementation (this is required for Roglo for instance), and then I will be able to drop v6.08.

Thanks again,

**Comment by chetmurthy** [comment]
Hmmm .... so, I don't know what you mean by "large databases" and such, but perhaps it's worth considering porting forward that support from your version, to GenWeb v7 ?

**Comment by hgouraud** [comment]
This is what I call gwc2 and it is being considered. I just have to be patient !!

Envoyé de mon iPhone
