### ISSUE TITLE
Quotation for attributes 

### ISSUE THREAD

**Issue by Kakadu** [camlp5/camlp5#96]
I wrote today the following...

````ocaml
(function 
| <:type_decl< $tp:ls$ $list:ltv$ = 'abstract >> -> ...
| <:type_decl< $tp:ls$ $list:ltv$ = $priv:b$ $t$ $_list:ltt$ >> -> ...
)
````
And it complains saying 
````
Warning 8 [partial-match]: this pattern-matching is not exhaustive.
Here is an example of a case that is not matched:
{tdIsDecl=VaVal true; tdNam=VaVal _; tdPrm=VaVal _; tdPrv=VaVal _; tdAttributes=VaVal (_::_); _ }
````

It looks like I'm matching a type declaration without attributes, bit in practice I want to get associated attributes in a pattern variable, or somehow specify explicitly that this type declaration should not have any attributes. 

I tried to get some information about it https://camlp5.github.io/doc/html-sphinx/ast_strict.html but couldn't manage find anything useful. Also, the listing for `type type_decl =` is being outdated. It would be great to update it and give a link to https://github.com/camlp5/camlp5/blob/master/main/mLast.mli (By some reason, I searched for this file longer than I wanted)

@chetmurthy

**Comment by chetmurthy** [comment]
OK, so first, I know  this isn't a good answer: a good answer would be pointing at documentation.  But still .... there's a test (try to) that I keep up-to-date, that covers all the pattern syntax.   So for type declarations, for the *raw* pattern ( https://github.com/camlp5/camlp5/blob/dcddf7027dc59091c13681d7acbad7ec036f86be/test/quot_r.out.ml#L1302 )
```
{MLast.tdIsDecl = b1; MLast.tdNam = ls; MLast.tdPrm = ltv; MLast.tdPrv = b2; MLast.tdDef = t; MLast.tdCon = ltt; MLast.tdAttributes = x};
```
the *quotation* ( https://github.com/camlp5/camlp5/blob/dcddf7027dc59091c13681d7acbad7ec036f86be/test/quot_r.ml#L1668 ):
```
<:type_decl<$_tp:ls$ $_list:ltv$ $_isdecl:b1$ $_priv:b2$ $t$ $_list:ltt$ $_itemattrs:x$ >>;
```
covers it.

So the bottom quotation, expanded,  is the top pattern.  As I change the AST, the top line is generated by a mechanical process, and then I have to manually update the file where the bottom line is found to match, so I learn whether I'm covering all syntax forms.  Sometimes not all syntax forms are covered, so in `quot_r.ml` you will find raw patterns instead of quotations.

Does this answer ?  [I mean, aside from "the docs need to be updated"]

**Comment by chetmurthy** [comment]
Just in case this is useful, I thought I'd mention this; if it's gibberish, then forget I wrote it.

BTW, for the general problem of "this unmatched case", when those cases are due to "vala",  you can eliminate those by using `pa_ppx.unmatched_vala`.  Here's an example: https://github.com/camlp5/pa_ppx/blob/40793f4b76e53375dd5bf424206f4577e05fa4b5/pa_deriving.plugins/pa_deriving_sexp.ml#L208
```
| [%unmatched_vala] -> failwith "pa_deriving_sexp.to_expression"
| ty ->
  Ploc.raise (loc_of_ctyp ty) (Failure (Printf.sprintf "pa_deriving_sexp.to_expression: %s" (Pp_MLast.show_ctyp ty)))
```
And what this means is that the first case will match any value that *would* have matched previous patterns, *except* that it contains `vala` `VaAnt` constructors.  The second case matches values that wouldn't have matched.  So you can distinguish between the case of "your AST contains antiquotations" (which regular OCaml code should not) and "your AST isn't handled by this code".

**Comment by Kakadu** [comment]
> BTW, for the general problem of "this unmatched case", when those cases are due to "vala",

Are you sure this happens because of "vala"? It looks like it happens both because of "vala" and me specyfing the absence of any attributes... 


Anyway, what is the most idiomatic way to write something like this?
```ocaml
      | <:type_decl< $tp:ls$ $list:ltv$ = $priv:b$ $t$ $_list:ltt$ $_itemattrs:attrs$ >> ->
          let VaVal attrs = attrs in
          let payload_expr = <:expr< gt ~{options = {gmap=gmap; show=show}} >> in
          let VaVal attrs = attrs in 
          (* ??? *)
          let attrs = VaVal (<:wunderwaffle< deriving $expr:payload_expr$ >> :: attrs) in
          (* ??? *)
          <:type_decl< $tp:ls$ $list:ltv$ = $priv:b$ $t$ $_list:ltt$ $itemattrs:attrs$  >>
```

**Comment by chetmurthy** [comment]
**three** answers:

1. I mis-spoke when I wrote "general problem".  I should have said "specific problem of this unmatched case *where* those cases are due to vala".  Sorry.

2. ARRGH, it turns out there's a bug in `pa_unmatched_vala`, and it doesn't work for records, only for constructors.  I'll have to fix it.  In the meantime, here's an example of what it does:

Suppose you have a function that takes apart a 2-tuple into the two expressions.  You want to handle all the other kinds of expressions (with an exception), but you *also* want to silence the "you didn't handle VaAnt" errors, b/c those should never occur, right?  So you write the code:

```
let foo = function
    <:expr< ($e1$, $e2$) >> -> (e1,e2)
| [%unmatched_vala] ->  failwith "why are you using VaAnt in real OCaml code?"
| e -> failwith "here we'd put in something to print out the unhandled expression"
;;
val foo : MLast.expr -> MLast.expr * MLast.expr = <fun>
```
And we'd get no match-errors.

3.  OK, your example.  First, I'm assuming that the second `let VaVal attrs = attrs` is a mistake.  I'm not sure what you're intending there.  Second, It looks like you want to concoct an attribute and add it to the attrs of this typedecl ?  So let's suppose that that's what you wanted to do.  So I'll write something that should work.   After it, I'll explain what it's doing.

```

let goo = function
 <:type_decl:< $tp:ls$ $list:ltv$ = $priv:b$ $t$ $list:ltt$ $itemattrs:attrs$ >> ->
  let (loc,_) = ls in
  let e = <:expr< f x >> in
  let a = <:attribute_body< goober $exp:e$ ; >> in
  let attrs = <:vala< a >> :: attrs in
  <:type_decl< $tp:ls$ $list:ltv$ = $priv:b$ $t$ $list:ltt$ $itemattrs:attrs$  >>
;;
Warning 8 [partial-match]: this pattern-matching is not exhaustive.
Here is an example of a case that is not matched:
{tdIsDecl=VaVal true; tdNam=VaVal (_, _); tdPrm=VaVal _; tdPrv=VaVal _;
tdCon=VaVal _; tdAttributes=VaAnt _; _ }
val goo : MLast.type_decl -> MLast.type_decl = <fun>
```
```

A. we're going to match a typedecl, and pull out the itemattrs.
B. NOTICE the "<:type_decl:<" (second colon): this signifies that the pattern should also have the "location" as the variable "loc".  But this doesn't work for type_decl, b/c there is no such location as the typedecl's members.  There is one as a *part* of one of the members, viz. `tdNam : V (loc * V string);` but it's covered by a `vala` it isn't guaranteed to be present, so we can't use it.  So for type_decl, the ":" doesn't work.
C. So we pull the "loc" out of the `ls`
D. then we concoct an expression (this is your "wunderwaffle")
E. And then we concoct an attribute-body
F. and then  wrap that in a vala (an attribute is `attribute_body vala`)
G. and then add it to the list `attrs`
H. and finally rebuild the type_decl.

Notice the warning 8.  This tells us that there are cases that aren't handled.  I'd like to use `unmatched_vala` to silence them, but that isn't going to work (for the moment).  So you can just put a `| _ -> raise an exception ...` or whatever you feel appropriate.

Does this help?  If not, please ask and I'll try again.

**Comment by chetmurthy** [comment]
OK, another response to your original question: in your original set of patterns, you said: "in practice I want to get associated attributes in a pattern variable, or somehow specify explicitly that this type declaration should not have any attributes."

1. to specify that it doesn't have any attributes, that is to say, the attribute-list is `[]`, you just do as you did above.  So for example, your second pattern expands to:
```
# {| <:type_decl< $tp:ls$ $list:ltv$ = $priv:b$ $t$ $_list:ltt$ >>  |} |> PAPR.Implem.pa1 |> PAPR.Implem.pr |> print_string ;;
let _ =
  {MLast.tdIsDecl = Ploc.VaVal true; MLast.tdNam = Ploc.VaVal ls;
   MLast.tdPrm = Ploc.VaVal ltv; MLast.tdPrv = Ploc.VaVal b; MLast.tdDef = t;
   MLast.tdCon = ltt; MLast.tdAttributes = Ploc.VaVal []}- : unit = ()
```
Notice that `tdAttributes = Ploc.VaVal []`.  That means "no attributes".

2. specify "I don't know what the attrs are, and I don't care, you write
```
<:type_decl< $tp:ls$ $list:ltv$ = $priv:b$ $t$ $_list:ltt$  $itemattrs:_x$ >>
```

So that's a variable `_x` that you can ignore.  Now, you might wonder why I didn't writ `$itemattrs:_$` and the truth is, that seems to trigger an error, and I need to look into why.  It should work, and it doesn't.

Hope this helps clarify your original question.

**Comment by chetmurthy** [comment]
OK, I made a mistake at the end there.  In *patterns*, OF COURSE, an antiqutation variable can be "_".  I mean, *OF COURSE*.  So you can write:
```
let goo = function
 <:type_decl:< $tp:ls$ $list:ltv$ = $priv:b$ $t$ $list:ltt$ $itemattrs:_$ >> ->
  let (loc,_) = ls in
  let e = <:expr< f x >> in
  let a = <:attribute_body< goober $exp:e$ ; >> in
  let attrs = [ <:vala< a >> ] in
  <:type_decl< $tp:ls$ $list:ltv$ = $priv:b$ $t$ $list:ltt$ $itemattrs:attrs$  >>
;;
```
[notice `$itemattrs:_$` at the top].  That works just fine.  What DOES NOT WORK (OF COURSE) is to use "_" as a variable in an expression-quotation.  It only works in pattern-quotations.  B/c "_" is a valid "pattern-variable" but not a valid "expression-variable".

**Comment by Kakadu** [comment]
I managed to implement what I need. Many thanks!

**Comment by chetmurthy** [comment]
Above I had mentioned that there was a bug in the `pa_ppx.unmatched_vala` rewriter that made it not work for patterns over record-types.  It was very straightforward to fix, and I've checked-in the change.  It'll go out with the next bugfix release of `pa_ppx`.  Here's what it does:

1. Imagine you write the following code:
```
let goo = function
 <:type_decl:< $tp:ls$ $list:ltv$ = $priv:b$ $t$ $list:ltt$ $itemattrs:attrs$ >> ->
  let (loc,_) = ls in
  let e = <:expr< f x >> in
  let a = <:attribute_body< goober $exp:e$ ; >> in
  let attrs = <:vala< a >> :: attrs in
  <:type_decl< $tp:ls$ $list:ltv$ = $priv:b$ $t$ $list:ltt$ $itemattrs:attrs$  >>
| [%unmatched_vala] ->  failwith "why are you using VaAnt in real OCaml code?"
```

2. after processing with the `pa_ppx.unmatched_vala` (the `camlp5.quotations`) processors, you get:
```
let goo =
  (function
     {MLast.tdIsDecl = Ploc.VaVal true; MLast.tdNam = Ploc.VaVal ls;
      MLast.tdPrm = Ploc.VaVal ltv; MLast.tdPrv = Ploc.VaVal b;
      MLast.tdDef = t; MLast.tdCon = Ploc.VaVal ltt;
      MLast.tdAttributes = Ploc.VaVal attrs} ->
       let (loc, _) = ls in
       let e =
         MLast.ExApp
           (loc, MLast.ExLid (loc, Ploc.VaVal "f"),
            MLast.ExLid (loc, Ploc.VaVal "x"))
       in
       let a =
         Ploc.VaVal (loc, "goober"),
         MLast.StAttr (loc, Ploc.VaVal [MLast.StExp (loc, e, Ploc.VaVal [])])
       in
       let attrs = Ploc.VaVal a :: attrs in
       {MLast.tdIsDecl = Ploc.VaVal true; MLast.tdNam = Ploc.VaVal ls;
        MLast.tdPrm = Ploc.VaVal ltv; MLast.tdPrv = Ploc.VaVal b;
        MLast.tdDef = t; MLast.tdCon = Ploc.VaVal ltt;
        MLast.tdAttributes = Ploc.VaVal attrs}
   | {MLast.tdIsDecl = Ploc.VaVal true | Ploc.VaAnt _;
      MLast.tdNam = Ploc.VaVal _ | Ploc.VaAnt _;
      MLast.tdPrm = Ploc.VaVal _ | Ploc.VaAnt _;
      MLast.tdPrv = Ploc.VaVal _ | Ploc.VaAnt _; MLast.tdDef = _;
      MLast.tdCon = Ploc.VaVal _ | Ploc.VaAnt _;
      MLast.tdAttributes = Ploc.VaVal _ | Ploc.VaAnt _} ->
       failwith "why are you using VaAnt in real OCaml code?")[@warning "-12"]- : unit = ()
```

3. Now if you look at the first and second branches, you'll see that each time in the first branch that a field has a `VaVal`, in the second branch that same field has a `VaVal _ | VaAnt _`.  This means that if in any place that matters to the first branch, you had put an antiquotation (so that the first branch would not match),  but otherwise the first branch was OK, then the "unmatched_vala" branch will match, and you'll get that `failwith`.

4. In this case it's pretty vacuous, but in the case I showed above with the `expr`:
```
let foo = function
    <:expr< ($e1$, $e2$) >> -> (e1,e2)
| [%unmatched_vala] ->  failwith "why are you using VaAnt in real OCaml code?"
| e -> failwith "here we'd put in something to print out the unhandled expression"
```

it expands to

```
let foo =
  (function
     MLast.ExTup (_, Ploc.VaVal [e1; e2]) -> e1, e2
   | MLast.ExTup (_, (Ploc.VaVal [_; _] | Ploc.VaAnt _)) ->
       failwith "why are you using VaAnt in real OCaml code?"
   | e ->
       failwith
         "here we'd put in something to print out the unhandled expression")[@warning "-12"]- : unit = ()
```

And here, the first branch covers only `ExTup` with a list of length two.  So the "unmatched_vala" branch only covers `ExTup` constructors, possibly with an antiquotation.  It does *not* cover any of the other constructors of that type (that's why we still need the third branch).

I use this rewriter a ton in `pa_ppx`, but obviously I haven't documented it.  If this is useful to you, I can write some documentation and tests.
